project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "*.md"

website:
  title: "The Neuroscience of Expertise"
  site-url: "https://neuroscienceofexpertise.com"
  favicon: images/Logo2.png
  
  navbar:
    logo: /images/Logo2.png
    title: The Neuroscience of Expertise
    background: "#536878"
    left:
      - href: About/index.qmd
        text: About
      - href: Research/index.qmd
        text: Research
      - href: Publications/index.qmd
        text: Publications
      - href: NeuroExpertise/index.qmd
        text: NoE Book
      - href: Blog/index.qmd
        text: Blog
    
  
  page-footer:
 # <span class="copyleft">&copy;</span>
   #![](/images/Logo2.png)
  # \uD83C\uDD2F
    left:  "Copyleft Merim Bilalić 2023"
    right:
      - icon: github
        href: https://github.com/MerimBilalic
      - icon: twitter
        href: https://twitter.com/MerimBilalic
    background: "#536878"

date-format: "D MMMM YYYY"
freeze: true


format:
  html:
    theme: tango
    css: styles.css
    toc: true
    html-math-method: katex
    include-in-header:
      file: header.html
