project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "*.md"

website:
  title: "The Neuroscience of Expertise"
  site-url: "https://neuroexpertise.com"
  navbar:
    background: "#536878"
    left:
      - href: About/index.qmd
        text: About
      - href: Research/index.qmd
        text: Research
      - href: Publications/index.qmd
        text: Publications
      - href: NeuroExpertise/index.qmd
        text: NeuroExpertise
      - href: Blog/index.qmd
        text: Blog

  page-footer:
    left: "Copyleft 2023, Merim Bilalić"
    right:
      - icon: github
        href: https://github.com/NoE
      - icon: twitter
        href: https://twitter.com/NoE
    background: "#536878"

date-format: "D MMMM YYYY"
freeze: true


format:
  html:
    theme: tango
    css: styles.css
    toc: true
    html-math-method: katex
    include-in-header:
      file: header.html
